config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get '/teams/:id/settings', to: 'teams#settings', as: 'team_settings'
  get '/leagues/:id/settings', to: 'leagues#settings', as: 'league_settings'
  get '/leagues/:id/rankings', to: 'leagues#rankings', as: 'league_rankings'
  get '/leagues/:id/history', to: 'leagues#history', as: 'league_history'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :teams
  resources :leagues do
    resources :posts
    resources :championships
  end
  resources :posts do
    resources :comments do
      member do
        put "like" => "comments#like"
      end
    end
    member do
      put "like" => "posts#like"
    end
  end
  
end

app/models/league.rb
class League < ApplicationRecord
  has_many :teams, dependent: :destroy
  has_many :users, through: :teams
  has_many :posts, dependent: :destroy
  has_many :championships, dependent: :destroy
  has_rich_text :content
end

app/controllers/leagues_controller.rb
class LeaguesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]

  def index
    @leagues = League.where(user: current_user)
    @allLeagues = League.all
  end

  def show
    @league = League.find(params[:id])
  end

  def rankings
    @league = League.find(params[:id])
    @posts = @league.posts
  end

  def history
    @league = League.find(params[:id])
  end

  def settings
    @league = League.find(params[:id])
  end

  def new
    @league = League.new
  end

  def create
    @league = League.new(league_params)
    if @league.save
      redirect_to league_path(@league)
    else
      render :new
    end
  end

  def edit
    @league = League.find(params[:id])
  end

  def update
    @league = League.find(params[:id])
    if @league.update(league_params)
      redirect_to league_path(@league)
    else
      render :edit
    end
  end

  def destroy
    @league = League.find(params[:id])
    @league.destroy
    redirect_to leagues_path
  end

  private

  def league_params
    params.require(:league).permit(:name, :user_id, :passcode, :description, :content)
  end
end

app/views/leagues/edit.html.erb
<%= render 'shared/league-nav' %>
<h2 class="mb-3"><%= @league.name %> Settings</h2>

<% if current_user.id == @league.user_id %>

<%= simple_form_for (@league) do |f| %>

  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.label :content, label: "Current Standings" %>
  <%= f.rich_text_area :content %>
  <%= f.input :passcode %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  
  <%= f.submit "Save Changes", class: "btn btn-light" %>
<% end %>

<% else %>

Sorry, only the commissioner has access to this page.

<% end %>

app/views/leagues/history.html.erb
<%= render 'shared/league-nav' %>
<div class="league-heading mb-3">
  <h1><%= @league.name %></h1>
  <h2>League History</h2>
  <% if @league.user_id == current_user.id %>
    <%= link_to "Crown a Champion >>", new_league_championship_path(@league) %>
  <% end %>
</div>

<div class="championship-grid">
  <% @league.championships.sort_by(&:year).reverse.each do |championship| %>
  <div class="championship-card">
    <div class="edit-delete-championship">
      <% if @league.user_id == current_user.id %>
        <div>
          <%= link_to edit_league_championship_path(id: championship.id, league_id: @league.id) do %>
          <i class="far fa-edit"></i>
          <% end %>
          <%= link_to league_championship_path(id: championship.id, league_id: @league.id),
            method: :delete,
            data: { confirm: 'Are you sure you want to delete this championship?'} do %>
            <div "></div>
            <i class="far fa-trash-alt"></i>
          <% end %>
        </div>
      <% end %>
    </div>
    <div class="championship-card-details">
      <div class="championship-card-year"><%= championship.year %></div>
      <div class="championship-card-user">
        <%= cl_image_tag user_avatar(championship.team.user, 100), class: "avatar-bordered-md mb-1" %>
        <div><%= championship.team.user.name %></div>
      </div>
      <div class="championship-card-trophy"><i class="fas fa-trophy fa-3x"></i></div>
    </div>
  </div>
<% end %>
</div>

app/views/leagues/index.html.erb
<h1>All Leagues</h1>
<ul class="league-list">
  <% @allLeagues.each do |league| %>
  <li>
    <div class="league-list-card">
      <div class="league-list-card-content">
        <p><%= league.name %></p>
      </div>
      <div class="league-list-card-links">
        <%= link_to "View League", league_path(league), class: "btn btn-light" %>
      </div>
    </div>
  </li>
  <% end %>
</ul>
<%= link_to "Create a League", new_league_path, class: "btn btn-light mt-3" %>

app/views/leagues/new.html.erb
<%= render 'shared/league-nav' %>
<%= simple_form_for (@league) do |f| %>

  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.label :content, label: "Current Standings" %>
  <%= f.rich_text_area :content %>
  <%= f.input :passcode %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  
  <%= f.submit "Save Changes" %>
<% end %>

app/views/leagues/rankings.html.erb
<%= render 'shared/league-nav' %>
<div class="league-heading mb-3">
  <h1><%= @league.name %></h1>
</div>

<h2 class="mb-3">Power Rankings</h2>


<% @league.posts.sort_by(&:created_at).reverse.each do |post| %>
  <% if post.post_type == "Power Rankings" %>
    <div class="post-preview-card">
        <div class="post-preview-card-content">
          <h3><%= post.title %></h3>
          <small>Posted by <%= post.author %> <%= time_ago_in_words(post.created_at)%> ago</small>
          
          <p><%= truncate(strip_tags(post.rich_text_content.to_s), length: 200) %>... <%= link_to "Full post >>", post_path(post) %></p>
        </div>
      </div>
  <% end %>
<% end %>

app/views/leagues/settings.html.erb
<h1>League Settings</h1>

<div class="league-actions">
  <%= link_to "Edit League Details", edit_league_path(@league), class: "btn btn-outline-light mb-1" %>
  <%= link_to "🗑", league_path(@league),
    method: :delete,
    data: { confirm: 'Are you sure you want to delete your league?'},
    class: "btn btn-outline-danger mb-1" 
  %>
  <%= link_to "Back to My League", league_path(@league), class: "btn btn-outline-light" %>
</div>

app/views/leagues/show.html.erb
<%= render 'shared/league-nav' %>
<div class="league-heading mb-3">
  <h1><%= @league.name %></h1>
  <%= link_to "ESPN Fantasy Home >>", 'https://www.espn.com/fantasy/' %>
  <br>
</div>

<% if @league.users.include?(current_user) %>

  <div class="row">
    <div class="col-lg-4 col-sm-12 mb-3 px-3">
       <h2 class="mb-3 text-center">Recent Posts</h2>
      <% if @league.posts.count == 0 %>
      <p>There aren't any posts yet!</p>
      <% else %>
        <% @league.posts.sort_by(&:created_at).reverse.first(5).each do |post| %>
      <div class="post-preview-card">
        <div class="post-preview-card-content">
          <h5><%= post.title %></h5>
          <small>Posted by <%= post.author %> <%= time_ago_in_words(post.created_at)%> ago</small>
          
          <p><%= truncate(strip_tags(post.rich_text_content.to_s), length: 50) %>... <%= link_to "Full post >>", post_path(post) %></p>
        </div>
      </div>
      <% end %>
      <% end %>
      
      <div class="league-actions">
        <%= link_to "New Post", new_league_post_path(@league), class: "btn btn-light mt-2 mr-1 mb-1" %>
        <%= link_to "All Posts", league_posts_path(@league), class: "btn btn-outline-light mt-2 mb-1" %>
      </div>

      
    </div>
    <div class="col-lg-4 col-sm-12 mb-3 px-3">
      <h2 class="mb-3 text-center">League Info</h2>
      <div class="league-info">
        <div class="league-description">
          <% if @league.description == "" %>
          <p>The league commissioner can update the league description in 
            <% if current_user.id == @league.user_id %>
            <%= link_to "league settings", edit_league_path(@league) %>
            <% else %>
            <span>league settings.</span>
            <% end %>
          </p>
          <% else %>
          <p><%= @league.description %></p>
          <% end %>
        </div>
        <hr class="horizontal-rule">
        <h3 class="text-center">Standings</h3>
        <div class="league-standings">
          <% if @league.content.nil? %>
            <p>The league commissioner can update the league standings in 
              <% if current_user.id == @league.user_id %>
              <%= link_to "league settings", edit_league_path(@league) %>
              <% else %>
              <span>league settings.</span>
              <% end %>
            </p> 
          <% else %> 
          <%= @league.content %>
          <% end %>
        </div>
      </div>
      
    </div>
  <div class="col-lg-4 col-sm-12 text-center px-3">
        
      <h2 class="mb-3">Teams</h2>
      <div class="teams-grid">
        <% @league.teams.each do |team| %>
        <div class="team-avatar">
          <%= link_to cl_image_tag(user_avatar(team.user, 100), class: "avatar-bordered-md"), team_path(team) %>
          <p><%= link_to team.hometown + " " + team.name, team_path(team), class: "team-link" %></p>
        </div>
      <% end %>
      </div>
    </div>
  </div>
<% else %>
<h2>Hi, <%= current_user.name %>. Please create a team to access league content.</h2>
<hr class="horizontal-rule">
<div class="league-show-links">
  <%= link_to "Create a Team", new_team_path, class: "btn btn-light mb-1 mt-3" %>
  <%= link_to "Back to Leagues", leagues_path, class: "btn btn-outline-light" %>
</div>
<% end %>