config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get '/teams/:id/settings', to: 'teams#settings', as: 'team_settings'
  get '/leagues/:id/settings', to: 'leagues#settings', as: 'league_settings'
  get '/leagues/:id/rankings', to: 'leagues#rankings', as: 'league_rankings'
  get '/leagues/:id/history', to: 'leagues#history', as: 'league_history'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :teams
  resources :leagues do
    resources :posts
    resources :championships
  end
  resources :posts do
    resources :comments do
      member do
        put "like" => "comments#like"
      end
    end
    member do
      put "like" => "posts#like"
    end
  end
  
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_league-nav.html.erb
<div class="league-nav">
  <div class="league-nav-items">
    <%= link_to "Dashboard", league_path(@league), class: "league-nav-item" %>
    <%= link_to "League History", league_history_path(@league), class: "league-nav-item" %>
    <%= link_to "Power Rankings", league_rankings_path(@league), class: "league-nav-item" %>
    <% if current_user.id == @league.user_id %>
      <%= link_to "League Settings", edit_league_path(@league), class: "league-nav-item" %>
    <% end %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-dark navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
  <i class="fas fa-football-ball fa-2x"></i>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Leagues", leagues_path, class: "nav-link" %>
        </li>
        <li class="nav-item mr-3">
          <%= link_to "My Teams", teams_path, class: "nav-link" %>
        </li>
         <li class="nav-item-user dropdown">
             <%= cl_image_tag user_avatar(current_user, 40), class: "avatar-bordered-sm dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <p class="dropdown-greeting">Hi, <%= current_user.name %></p>
            <hr class="horizontal-rule">
            <%= link_to "Account", edit_user_registration_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_team-nav.html.erb
<div class="team-nav">
  <div class="team-nav-items">
    <%= link_to "Dashboard", team_path(@team), class: "team-nav-item" %>
    <%= link_to "My Teams", teams_path, class: "team-nav-item" %>
    <%= link_to "League Dashboard", league_path(@team.league), class: "team-nav-item" %>
  </div>
</div>