config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get '/teams/:id/settings', to: 'teams#settings', as: 'team_settings'
  get '/leagues/:id/settings', to: 'leagues#settings', as: 'league_settings'
  get '/leagues/:id/rankings', to: 'leagues#rankings', as: 'league_rankings'
  get '/leagues/:id/history', to: 'leagues#history', as: 'league_history'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :teams
  resources :leagues do
    resources :posts
    resources :championships
  end
  resources :posts do
    resources :comments do
      member do
        put "like" => "comments#like"
      end
    end
    member do
      put "like" => "posts#like"
    end
  end
  
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :league
  has_many :comments, dependent: :destroy
  has_rich_text :content
  has_one_attached :document
  acts_as_votable
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  respond_to :js, :html, :json

  def index
    @league = League.find(params[:league_id])
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @comments = @post.comments
    @user = current_user
  end

  def like
    @user = current_user
    @post = Post.find(params[:id])
    if params[:format] == 'like'
      @post.liked_by @user
    elsif params[:format] == 'unlike'
      @post.unliked_by @user
    end
    redirect_to post_path(@post)
  end

  def new
    @league = League.find(params[:league_id])
    @leagues = League.all
    @post = Post.new
    @post_types = ['Power Rankings', 'Regular Post']
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to post_path(@post)
    else
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
    @post_types = ['Power Rankings', 'Regular Post']
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to post_path(@post)
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    post = @post
    @post.destroy
    redirect_to league_path(post.league)
  end

  private

  def post_params
    params.require(:post).permit(:title, :author, :content, :league_id, :user_id, :post_type, :document)
  end

end

app/views/posts/edit.html.erb
<div class="league-nav">
  <div class="league-nav-items">
    <%= link_to "Dashboard", league_path(@post.league), class: "league-nav-item" %>
    <%= link_to "League History", league_history_path(@post.league), class: "league-nav-item" %>
    <%= link_to "Power Rankings", league_rankings_path(@post.league), class: "league-nav-item" %>
    <% if current_user.id == @post.league.user_id %>
      <%= link_to "League Settings", edit_league_path(@post.league), class: "league-nav-item" %>
    <% end %>
  </div>
</div>
<h2>Edit Post</h2>

<%= simple_form_for (@post) do |f| %>

  <%= f.input :post_type, label: "Post Type", as: :radio_buttons, collection: @post_types %>
  <%= f.input :title %>
  <%= f.hidden_field :author, value: current_user.name %>
  <%= f.label :document %>
  <%= f.file_field :document %>
  <%= f.label :content %>
  <%= f.rich_text_area :content %>
  <%= f.hidden_field :league_id, value: @post.league_id %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  
  <%= f.submit "Update and Share", class: "btn btn-light mt-3 mb-1" %>
<% end %>
<%= link_to "Cancel", post_path(@post), class: "btn btn-outline-light" %>

app/views/posts/index.html.erb
<%= render 'shared/league-nav' %>
<h2 class="mb-3">All Posts in <%= @league.name %></h2>

<% @league.posts.sort_by(&:created_at).reverse.each do |post| %>
  <div class="post-preview-card">
        <div class="post-preview-card-content">
          <h5><%= post.title %></h5>
          <small>Posted by <%= post.author %> <%= time_ago_in_words(post.created_at)%> ago</small>
          
          <p><%= truncate(strip_tags(post.rich_text_content.to_s), length: 50) %>... <%= link_to "Full post >>", post_path(post) %></p>
        </div>
      </div>
<% end %>
<div class="league-actions">
  <%= link_to "New Post", new_league_post_path(@league), class: "btn btn-light mt-2 mb-1" %>
</div>

app/views/posts/new.html.erb
<%= render 'shared/league-nav' %>
<h2>Create a post</h2>

<%= simple_form_for [ @league, @post ] do |f| %>

  <%= f.input :post_type, label: false, as: :radio_buttons, collection: @post_types %>
  <%= f.input :title %>
  <%= f.hidden_field :author, value: current_user.name %>
  <%= f.label :document, label: "PDF" %>
  <%= f.file_field :document %>
  <br>
  <%= f.label :content %>
  <%= f.rich_text_area :content %>
  <br>
  <%= f.hidden_field :league_id, value: @league.id %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  
  <%= f.submit "Share", class: "btn btn-light" %>
<% end %>

app/views/posts/show.html.erb
<div class="league-nav">
  <div class="league-nav-items">
    <%= link_to "Dashboard", league_path(@post.league), class: "league-nav-item" %>
    <%= link_to "League History", league_history_path(@post.league), class: "league-nav-item" %>
    <%= link_to "Power Rankings", league_rankings_path(@post.league), class: "league-nav-item" %>
    <% if current_user.id == @post.league.user_id %>
      <%= link_to "League Settings", edit_league_path(@post.league), class: "league-nav-item" %>
    <% end %>
  </div>
</div>


<div class="mb-3">
  <div class="post-heading">
    <h1 class="mr-3"><%= @post.title %></h1>
    <% if @post.user == current_user %>
    <div>
      <%= link_to edit_post_path(@post) do %>
      <i class="far fa-edit"></i>
      <% end %>
      <%= link_to post_path(@post),
        method: :delete,
        data: { confirm: 'Are you sure you want to delete your post?'} do %>
        <i class="far fa-trash-alt"></i>
      <% end %>
    </div>
    <% end %>
  </div>
  
  <h3>By: <%= @post.author %></h3>
  <small>Posted by <%= @post.author %> <%= time_ago_in_words(@post.created_at)%> ago</small>
  <% if @post.document.attached? %>
  <p><%= link_to "See attached PDF", @post.document %></p>
  <% end %>
  <p><%= @post.content %></p>

  <div class="post-likes">
  <% if current_user.liked? @post %>
    <%= link_to "Unlike Post", like_post_path(@post, 'unlike'), method: :put, class: "btn btn-light mr-2" %>
    <% else %>
    <%= link_to "Like Post", like_post_path(@post, 'like'), method: :put, class: "btn btn-light mr-2" %>
  <% end %>
  <div class="mr-3">
    ♥️
    <%= @post.get_likes.size %>
  </div>
</div>
</div>

<div id="comment-module">
  
  <%= simple_form_for [ @post, @comment ] do |f| %>

  <%= f.hidden_field :author, value: current_user.name %>
  <%= f.hidden_field :post_id, value: @post.id %>
  <%= f.hidden_field :user_id, value: @user.id %>
  <%= f.input :content, as: :string, rows: 1, class: "comment-input mb-1", placeholder: 'Write a comment...', label: false %>
  <%= f.submit "Comment", class: "btn btn-light comment-submit mb-3" %>
  <% end %>

  <% @post.comments.sort_by(&:created_at).each do |comment| %>
  <div class="comment-module">
    <%= cl_image_tag(user_avatar(comment.user, size=40), class: "avatar-bordered-sm mr-3") %>
    <div class="comment-card">
      <div class="comment-card-details">
        <small><strong><%= comment.author %></strong> | <%= time_ago_in_words(comment.created_at) %> ago</small>
        <p><%= comment.content %></p>
      </div>
      <div class="comment-likes">
        <% if current_user.liked? comment %>
          <%= link_to "Unlike", like_post_comment_path(post_id: @post.id, comment_id: comment.id, format: 'unlike'), method: :put, class: "btn btn-light mr-2" %>
          <% else %>
          <%= link_to "Like", like_post_comment_path(post_id: @post.id, comment_id: comment.id, format: 'like'), method: :put, class: "btn btn-light mr-2" %>
        <% end %>
        <div class="mr-3">
          ♥️
          <%= comment.get_likes.size %>
        </div>
        <% if comment.user_id == current_user.id %>
        <%= link_to "🗑", post_comment_path(id: comment.id, post_id: @post.id), method: :delete,
          data: { confirm: 'Are you sure you want to delete this comment?'} %>
        <% end %>
      </div>
    
  </div>
</div>
  
<% end %>
</div>


<%= javascript_pack_tag 'comments' %>